AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/schema.rb
Rails:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/TrailingWhitespace:
  Enabled: false
Metrics/LineLength:
  Enabled: false
