inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/schema.rb
Rails:
  Enabled: true

Metrics/LineLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/TrailingWhitespace:
  # Editor handles this. Rubocop complains too much.
  Enabled: false
