AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/schema.rb
Rails:
  Enabled: true

# Editor handles this. Rubocop complains too much.
TrailingWhitespace:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false
